language: node_js
dist: trusty
node_js:
  - "node"
  - "lts/*"
script:
  - npm run test
cache:
  directories:
  - node_modules
env:
  global:
  - POWERAI_VISION_WEB_API_URL=:/test/AIVision/api/dlapis/fake
